### PR TITLE
prerelease-2

### PR DESCRIPTION
**Pull request by Ernaldis**
Steps taken:

- `kubectl -n sci-viz-public create configmap sci-viz-config --from-file=ibl_spec_public.yaml -o yaml --dry-run=client | kubectl -n sci-viz-public apply -f -`
- `kubectl -n sci-viz-public apply -f pharus/ -f sci-viz/`

### CODE REVIEW

**Comment by guzman-raphael** [comment]
> Steps taken:
>  - kubectl -n sci-viz-public create configmap sci-viz-config --from-file=ibl_spec_public.yaml -o yaml --dry-run=client | kubectl -n sci-viz-public apply -f -

This command won't work for you for the following reasons:
- The deployments are expecting the file to be named `sci-viz-config.yaml`. Your command generated the config map with a file of a different name so the key by default uses the name of the file which won't match. There may be a flag to modify this but simplest way to simply rename the file to match
- When you used `apply`, the CM already existed and saw that you had a new key. This meant it added the new key for the different file name which the other deployments aren't expecting.

**Comment by Ernaldis** [comment]
I see, I thought doing this would overwrite the old configmap. I'll rename the file and run it again.

**Comment by guzman-raphael** [comment]
You will likely need to `delete -> apply` the old CM so you can get rid of the accidental key too.

**Comment by Ernaldis** [comment]
Looks like the table is working now. Thank you for your help!

**Comment by guzman-raphael** [comment]
Checking the docs, you might wanna update your command reference to the following. It would have done the trick:

```bash
kubectl -n sci-viz-public create configmap sci-viz-config --from-file=sci-viz-config.yaml=ibl_spec_public.yaml -o yaml --dry-run=client | kubectl -n sci-viz-public apply -f -
```

**Review by guzman-raphael — APPROVED** [review]

**Pull request merged**
